### ISSUE TITLE
Usable as a library

### ISSUE THREAD

**Issue by magicalbanana** [StabbyCutyou/moldova#13]
It would be great if this was usable as a library to aide in creating the setup necessary for integration tests or possibly end to end testing.

**Comment by StabbyCutyou** [comment]
So, the aim was to make it useable as a library - you should be able to import it and use it like the cmd executable does.

But, this feature is underserved, and there is probably a cleaner API I could have to make working with it better.

Are there any specific bugs at this moment preventing you from using it as a lib?

**Comment by StabbyCutyou** [comment]
https://github.com/StabbyCutyou/moldova/blob/master/cmd/moldova/moldova.go

Could you take a look here, and let me know what you think a better pattern would be?

**Comment by StabbyCutyou** [comment]
I'm gonna close this due to inactivity. If you're still having problems running as a binary, please re-open with more details.
